services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: lab6-server

    environment:
      DB_URL: jdbc:postgresql://pg:5438/studs
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      LOG_LEVEL: info
    ports:
      - "5555:5555"
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  # docker compose run --rm client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      HOST: server
      PORT: "5555"
    stdin_open: true
    tty: true
    depends_on:
      server:
        condition: service_started
