FROM eclipse-temurin:17-jre
WORKDIR /app

# Подтягиваем ГОТОВЫЙ fat-jar и конфиг логгера
COPY LabCode/src/server/target/server.jar /app/server.jar
COPY resources/log4j2.xml              /app/config/log4j2.xml

# Настройки логирования (уровень можно менять через переменную LOG_LEVEL)
ENV JAVA_OPTS="-Xms128m -Xmx512m \
 -Dlog4j.configurationFile=file:/app/config/log4j2.xml \
 -DLOG_LEVEL=${LOG_LEVEL:-info}"

EXPOSE 5555
CMD ["sh","-lc","java $JAVA_OPTS -jar /app/server.jar"]
